theme: jekyll-theme-minimal
title: KyleCox26's homepage
description: Bookmark this to keep an eye on my project updates!

#My First Ever Github Page
  This is my first time making a Github Page

## My Interests
  -Snowboarding
  -Skating
  -Vehicles
## This is where I'm from
![IDAHO](KyleCox26.github.io/images/idahoFlag.png)


